### ISSUE TITLE
lein test fails, need to add "with-profile +sample"

### ISSUE THREAD

**Issue by TimoFreiberg** [cloverage/cloverage#221]
The test `test-cyclic-dependency` fails when the `sample` profile is not enabled, because it doesn't find the file.
Could we either add the `{:source-paths ["sample"]}` setting to the `test` profile or move the `cyclic_dependency.clj` file into the `test/cloverage/sample` directory?

I actually did the latter to fix the issue before I checked which profile is used by travis and found the `sample` profile, so I could easily create a PR for that fix :)

----

Alright, I found a comment explaining the separate directory:
> "with-profile +sample" is needed to pull in a file with circular dependencies
> that the eastwood check (see below) isn't able to instrument.

Does that make it impossible to get `lein test` to run?

**Comment by lvh** [comment]
FYI: I have no idea if there's a good reason why that profile/directory needs to exist. I imagine it's because it breaks some CI tools and so you want that in a separate directory, but that doesn't explain why you wouldn't just add a :source-path to :test as you suggest. I'd be happy to take a PR that adds the source path and gets rid of the :sample profile, which appears to be what you suggest.

**Comment by matt-y** [comment]
Moving the `cyclic_dependency.clj` into the `test/cloverage/sample` is reasonable, but as lvh mentioned, it does in fact cause a CI breakage. There's an issue open against eastwood tracking this: https://github.com/jonase/eastwood/issues/252. To get around that issue the eastwood invocation in the `.travis.yml` CI file would have to exclude that namespace (which it implicitly does in the current organization of these files).
